/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Menus;

import Controle.AlunoDAO;
import Modelo.Aluno;
import static Visao.JFrame_login.user;
import java.sql.SQLException;

/**
 *
 * @author Anderson
 */
public class JFrame_aluno extends javax.swing.JFrame {
       AlunoDAO controle = new AlunoDAO();
       Aluno model = new Aluno();
    /**
     * Creates new form JFrame_aluno
     */
    public JFrame_aluno() {
        initComponents();        
        setLocationRelativeTo(null);
         setSize(927, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_bemvindoAluno = new javax.swing.JLabel();
        jB_turma = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jB_turma1 = new javax.swing.JButton();
        jB_turma2 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jB_turma3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 234, 234));
        setName("Aluno"); // NOI18N
        getContentPane().setLayout(null);

        jL_bemvindoAluno.setBackground(new java.awt.Color(36, 44, 68));
        jL_bemvindoAluno.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jL_bemvindoAluno.setForeground(new java.awt.Color(255, 255, 255));
        jL_bemvindoAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_bemvindoAluno.setText("Bem-vindo");
        jL_bemvindoAluno.setOpaque(true);
        getContentPane().add(jL_bemvindoAluno);
        jL_bemvindoAluno.setBounds(0, 0, 920, 57);

        jB_turma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/Aluno_EditarDados.fw.png"))); // NOI18N
        jB_turma.setFocusable(false);
        jB_turma.setOpaque(false);
        jB_turma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_turmaActionPerformed(evt);
            }
        });
        getContentPane().add(jB_turma);
        jB_turma.setBounds(540, 310, 120, 70);

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 46, 68));
        jLabel3.setText("Matricular");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(570, 220, 70, 27);

        jB_turma1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/Aluno_historico.fw.png"))); // NOI18N
        jB_turma1.setFocusable(false);
        jB_turma1.setOpaque(false);
        jB_turma1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_turma1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_turma1);
        jB_turma1.setBounds(250, 310, 120, 70);

        jB_turma2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/Aluno_turma.fw.png"))); // NOI18N
        jB_turma2.setFocusable(false);
        jB_turma2.setOpaque(false);
        jB_turma2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_turma2ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_turma2);
        jB_turma2.setBounds(250, 150, 120, 70);

        jLabel4.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(36, 46, 68));
        jLabel4.setText("Meus dados");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(560, 380, 90, 27);

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 46, 68));
        jLabel5.setText("Turma");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(280, 220, 50, 27);

        jB_turma3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/Aluno_matTurma.fw.png"))); // NOI18N
        jB_turma3.setFocusable(false);
        jB_turma3.setOpaque(false);
        jB_turma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_turma3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_turma3);
        jB_turma3.setBounds(540, 150, 120, 70);

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 46, 68));
        jLabel6.setText("Histórico");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(280, 380, 70, 27);

        setSize(new java.awt.Dimension(938, 583));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_turmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_turmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_turmaActionPerformed

    private void jB_turma1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_turma1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_turma1ActionPerformed

    private void jB_turma2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_turma2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_turma2ActionPerformed

    private void jB_turma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_turma3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_turma3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_aluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_aluno().setVisible(true);
            }
        });
    }
public void bemvindo() throws SQLException{
    model = controle.buscarAluno(user);
    String jL_nome = null;
    if(model!=null){
       jL_nome = model.getNome();
    }
    jL_bemvindoAluno.setText("Bem vindo "+jL_nome);
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_turma;
    private javax.swing.JButton jB_turma1;
    private javax.swing.JButton jB_turma2;
    private javax.swing.JButton jB_turma3;
    private javax.swing.JLabel jL_bemvindoAluno;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
