/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao.Menus;

import Controle.AdmDAO;
import Controle.AlunoDAO;
import Modelo.Administrador;
import Visao.JFrameAlterarAdministrador;
import Visao.JFrameAlterarAluno;
import Visao.JFrameAlterarCurso;
import Visao.JFrameAlterarProfessor;
import Visao.JFrameCadastrarAluno;
import Visao.JFrameCadastrarCurso;
import static Visao.JFrame_login.user;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Anderson
 */
public class JFrame_adm extends javax.swing.JFrame {

    AdmDAO controle = new AdmDAO();
    Administrador model = new Administrador();
    boolean statusjB_curso = false;
    boolean statusjB_prof = false;
    boolean statusjB_aluno = false;
    boolean statusjB_disciplina = false;
    boolean statusjB_turma = false;
    boolean statusjB_adm = false;

    /**
     * Creates new form JFrame_aluno
     */
    public JFrame_adm() {
        initComponents();
        setLocationRelativeTo(null);
        botoesInvisivel();
        // setSize(927, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jL_bemvindoAluno = new javax.swing.JLabel();
        jB_curso = new javax.swing.JButton();
        jB_prof = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jB_turma3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jB_turma4 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jB_turma5 = new javax.swing.JButton();
        jB_aluno = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jB_listCurso = new javax.swing.JButton();
        jB_addCurso = new javax.swing.JButton();
        jB_editCurso = new javax.swing.JButton();
        jB_addProf = new javax.swing.JButton();
        jB_editProf = new javax.swing.JButton();
        jB_listProf = new javax.swing.JButton();
        jB_addAluno = new javax.swing.JButton();
        jB_editAluno = new javax.swing.JButton();
        jB_listAluno = new javax.swing.JButton();
        jB_listAdm = new javax.swing.JButton();
        jB_editAdm = new javax.swing.JButton();
        jB_addAdm = new javax.swing.JButton();
        jB_listDisc = new javax.swing.JButton();
        jB_editDisc = new javax.swing.JButton();
        jB_addDisc = new javax.swing.JButton();
        jB_addTurma = new javax.swing.JButton();
        jB_editTurma = new javax.swing.JButton();
        jB_listTurma = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(234, 234, 234));
        setName("Aluno"); // NOI18N
        getContentPane().setLayout(null);

        jL_bemvindoAluno.setBackground(new java.awt.Color(36, 44, 68));
        jL_bemvindoAluno.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jL_bemvindoAluno.setForeground(new java.awt.Color(255, 255, 255));
        jL_bemvindoAluno.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jL_bemvindoAluno.setText("Bem-vindo");
        jL_bemvindoAluno.setOpaque(true);
        getContentPane().add(jL_bemvindoAluno);
        jL_bemvindoAluno.setBounds(0, 0, 920, 57);

        jB_curso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/Adm_Curso.fw.png"))); // NOI18N
        jB_curso.setFocusable(false);
        jB_curso.setOpaque(false);
        jB_curso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cursoActionPerformed(evt);
            }
        });
        getContentPane().add(jB_curso);
        jB_curso.setBounds(200, 390, 120, 70);

        jB_prof.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/Adm_Professor.fw.png"))); // NOI18N
        jB_prof.setFocusable(false);
        jB_prof.setOpaque(false);
        jB_prof.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_profActionPerformed(evt);
            }
        });
        getContentPane().add(jB_prof);
        jB_prof.setBounds(200, 190, 120, 70);

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 46, 68));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Administrador");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(590, 260, 120, 27);

        jB_turma3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/Adm_Administrador.fw.png"))); // NOI18N
        jB_turma3.setFocusable(false);
        jB_turma3.setOpaque(false);
        jB_turma3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_turma3ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_turma3);
        jB_turma3.setBounds(590, 190, 120, 70);

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 46, 68));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Curso");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(200, 460, 120, 27);

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 46, 68));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Professor");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(200, 260, 120, 27);

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 46, 68));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Disciplina");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(400, 460, 120, 27);

        jB_turma4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/Adm_Disciplina.fw.png"))); // NOI18N
        jB_turma4.setFocusable(false);
        jB_turma4.setOpaque(false);
        jB_turma4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_turma4ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_turma4);
        jB_turma4.setBounds(400, 390, 120, 70);

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 46, 68));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Turma");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(580, 460, 120, 27);

        jB_turma5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/Aluno_turma.fw.png"))); // NOI18N
        jB_turma5.setFocusable(false);
        jB_turma5.setOpaque(false);
        jB_turma5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_turma5ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_turma5);
        jB_turma5.setBounds(580, 390, 120, 70);

        jB_aluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/Adm_Aluno.fw.png"))); // NOI18N
        jB_aluno.setFocusable(false);
        jB_aluno.setOpaque(false);
        jB_aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_alunoActionPerformed(evt);
            }
        });
        getContentPane().add(jB_aluno);
        jB_aluno.setBounds(400, 190, 120, 70);

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 46, 68));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Aluno");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(400, 260, 120, 27);

        jB_listCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/lista.fw.png"))); // NOI18N
        jB_listCurso.setToolTipText("Listar");
        jB_listCurso.setBorder(null);
        jB_listCurso.setBorderPainted(false);
        jB_listCurso.setFocusable(false);
        jB_listCurso.setVisible(false);
        jB_listCurso.setOpaque(false);
        getContentPane().add(jB_listCurso);
        jB_listCurso.setBounds(290, 350, 30, 30);

        jB_addCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/add.fw.png"))); // NOI18N
        jB_addCurso.setToolTipText("Cadastrar Curso");
        jB_addCurso.setBorder(null);
        jB_addCurso.setBorderPainted(false);
        jB_addCurso.setFocusable(false);
        jB_addCurso.setVisible(false);
        jB_addCurso.setOpaque(false);
        jB_addCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_addCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jB_addCurso);
        jB_addCurso.setBounds(210, 350, 30, 30);

        jB_editCurso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/editar.fw.png"))); // NOI18N
        jB_editCurso.setToolTipText("Editar Curso");
        jB_editCurso.setBorder(null);
        jB_editCurso.setBorderPainted(false);
        jB_editCurso.setFocusable(false);
        jB_editCurso.setVisible(false);
        jB_editCurso.setOpaque(false);
        jB_editCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jB_editCurso);
        jB_editCurso.setBounds(250, 350, 30, 30);

        jB_addProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/add.fw.png"))); // NOI18N
        jB_addProf.setToolTipText("Cadastrar Professor");
        jB_addProf.setBorder(null);
        jB_addProf.setBorderPainted(false);
        jB_addProf.setFocusable(false);
        jB_addProf.setOpaque(false);
        jB_addProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_addProfActionPerformed(evt);
            }
        });
        getContentPane().add(jB_addProf);
        jB_addProf.setBounds(210, 150, 30, 30);

        jB_editProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/editar.fw.png"))); // NOI18N
        jB_editProf.setToolTipText("Editar Professor");
        jB_editProf.setBorder(null);
        jB_editProf.setBorderPainted(false);
        jB_editProf.setFocusable(false);
        jB_editProf.setOpaque(false);
        jB_editProf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editProfActionPerformed(evt);
            }
        });
        getContentPane().add(jB_editProf);
        jB_editProf.setBounds(250, 150, 30, 30);

        jB_listProf.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/lista.fw.png"))); // NOI18N
        jB_listProf.setToolTipText("Listar Professor");
        jB_listProf.setBorder(null);
        jB_listProf.setBorderPainted(false);
        jB_listProf.setFocusable(false);
        jB_listProf.setOpaque(false);
        getContentPane().add(jB_listProf);
        jB_listProf.setBounds(290, 150, 30, 30);

        jB_addAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/add.fw.png"))); // NOI18N
        jB_addAluno.setToolTipText("Cadastrar Aluno");
        jB_addAluno.setBorder(null);
        jB_addAluno.setBorderPainted(false);
        jB_addAluno.setFocusable(false);
        jB_addAluno.setOpaque(false);
        jB_addAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_addAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jB_addAluno);
        jB_addAluno.setBounds(410, 150, 30, 30);

        jB_editAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/editar.fw.png"))); // NOI18N
        jB_editAluno.setToolTipText("Editar Aluno");
        jB_editAluno.setBorder(null);
        jB_editAluno.setBorderPainted(false);
        jB_editAluno.setFocusable(false);
        jB_editAluno.setOpaque(false);
        jB_editAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jB_editAluno);
        jB_editAluno.setBounds(450, 150, 30, 30);

        jB_listAluno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/lista.fw.png"))); // NOI18N
        jB_listAluno.setToolTipText("Listar Aluno");
        jB_listAluno.setBorder(null);
        jB_listAluno.setBorderPainted(false);
        jB_listAluno.setFocusable(false);
        jB_listAluno.setOpaque(false);
        getContentPane().add(jB_listAluno);
        jB_listAluno.setBounds(490, 150, 30, 30);

        jB_listAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/lista.fw.png"))); // NOI18N
        jB_listAdm.setToolTipText("Listar Administrador");
        jB_listAdm.setBorder(null);
        jB_listAdm.setBorderPainted(false);
        jB_listAdm.setFocusable(false);
        jB_listAdm.setOpaque(false);
        getContentPane().add(jB_listAdm);
        jB_listAdm.setBounds(680, 150, 30, 30);

        jB_editAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/editar.fw.png"))); // NOI18N
        jB_editAdm.setToolTipText("Editar Administrador");
        jB_editAdm.setBorder(null);
        jB_editAdm.setBorderPainted(false);
        jB_editAdm.setFocusable(false);
        jB_editAdm.setOpaque(false);
        jB_editAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editAdmActionPerformed(evt);
            }
        });
        getContentPane().add(jB_editAdm);
        jB_editAdm.setBounds(640, 150, 30, 30);

        jB_addAdm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/add.fw.png"))); // NOI18N
        jB_addAdm.setToolTipText("Cadastrar Administrador");
        jB_addAdm.setBorder(null);
        jB_addAdm.setBorderPainted(false);
        jB_addAdm.setFocusable(false);
        jB_addAdm.setOpaque(false);
        jB_addAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_addAdmActionPerformed(evt);
            }
        });
        getContentPane().add(jB_addAdm);
        jB_addAdm.setBounds(600, 150, 30, 30);

        jB_listDisc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/lista.fw.png"))); // NOI18N
        jB_listDisc.setToolTipText("Listar Disciplina");
        jB_listDisc.setBorder(null);
        jB_listDisc.setBorderPainted(false);
        jB_listDisc.setFocusable(false);
        jB_listDisc.setOpaque(false);
        getContentPane().add(jB_listDisc);
        jB_listDisc.setBounds(490, 350, 30, 30);

        jB_editDisc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/editar.fw.png"))); // NOI18N
        jB_editDisc.setToolTipText("Editar Disciplina");
        jB_editDisc.setBorder(null);
        jB_editDisc.setBorderPainted(false);
        jB_editDisc.setFocusable(false);
        jB_editDisc.setOpaque(false);
        jB_editDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editDiscActionPerformed(evt);
            }
        });
        getContentPane().add(jB_editDisc);
        jB_editDisc.setBounds(450, 350, 30, 30);

        jB_addDisc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/add.fw.png"))); // NOI18N
        jB_addDisc.setToolTipText("Cadastrar Disciplina");
        jB_addDisc.setBorder(null);
        jB_addDisc.setBorderPainted(false);
        jB_addDisc.setFocusable(false);
        jB_addDisc.setOpaque(false);
        jB_addDisc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_addDiscActionPerformed(evt);
            }
        });
        getContentPane().add(jB_addDisc);
        jB_addDisc.setBounds(410, 350, 30, 30);

        jB_addTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/add.fw.png"))); // NOI18N
        jB_addTurma.setToolTipText("Cadastrar Turma");
        jB_addTurma.setBorder(null);
        jB_addTurma.setBorderPainted(false);
        jB_addTurma.setFocusable(false);
        jB_addTurma.setOpaque(false);
        jB_addTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_addTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(jB_addTurma);
        jB_addTurma.setBounds(590, 350, 30, 30);

        jB_editTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/editar.fw.png"))); // NOI18N
        jB_editTurma.setToolTipText("Editar Turma");
        jB_editTurma.setBorder(null);
        jB_editTurma.setBorderPainted(false);
        jB_editTurma.setFocusable(false);
        jB_editTurma.setOpaque(false);
        jB_editTurma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_editTurmaActionPerformed(evt);
            }
        });
        getContentPane().add(jB_editTurma);
        jB_editTurma.setBounds(630, 350, 30, 30);

        jB_listTurma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/lista.fw.png"))); // NOI18N
        jB_listTurma.setToolTipText("Listar Turma");
        jB_listTurma.setBorder(null);
        jB_listTurma.setBorderPainted(false);
        jB_listTurma.setFocusable(false);
        jB_listTurma.setOpaque(false);
        getContentPane().add(jB_listTurma);
        jB_listTurma.setBounds(670, 350, 30, 30);

        setSize(new java.awt.Dimension(938, 583));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_cursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cursoActionPerformed
        // TODO add your handling code here:
        if (statusjB_curso == false) {
            botoesInvisivel();
            statusFalse();
            statusjB_curso = true;
            jB_addCurso.setVisible(true);
            jB_editCurso.setVisible(true);
            jB_listCurso.setVisible(true);
        } else {
            statusFalse();
            botoesInvisivel();
        }
    }//GEN-LAST:event_jB_cursoActionPerformed

    private void jB_profActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_profActionPerformed
        // TODO add your handling code here:
        if (statusjB_prof == false) {
            botoesInvisivel();
            statusFalse();
            statusjB_prof = true;
            jB_addProf.setVisible(true);
            jB_editProf.setVisible(true);
            jB_listProf.setVisible(true);
        } else {
            statusFalse();
            botoesInvisivel();
        }

    }//GEN-LAST:event_jB_profActionPerformed

    private void jB_turma3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_turma3ActionPerformed
        // TODO add your handling code here:
        if (statusjB_adm == false) {
            botoesInvisivel();
            statusFalse();
            statusjB_adm = true;
            jB_addAdm.setVisible(true);
            jB_editAdm.setVisible(true);
            jB_listAdm.setVisible(true);
        } else {
            statusFalse();
            botoesInvisivel();
        }
    }//GEN-LAST:event_jB_turma3ActionPerformed

    private void jB_turma4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_turma4ActionPerformed
        // TODO add your handling code here:
        if (statusjB_disciplina == false) {
            botoesInvisivel();
            statusFalse();
            statusjB_disciplina = true;
            jB_addDisc.setVisible(true);
            jB_editDisc.setVisible(true);
            jB_listDisc.setVisible(true);
        } else {
            statusFalse();
            botoesInvisivel();
        }
    }//GEN-LAST:event_jB_turma4ActionPerformed

    private void jB_turma5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_turma5ActionPerformed
        // TODO add your handling code here:
        if (statusjB_turma == false) {
            botoesInvisivel();
            statusFalse();
            statusjB_turma = true;
            jB_addTurma.setVisible(true);
            jB_editTurma.setVisible(true);
            jB_listTurma.setVisible(true);
        } else {
            statusFalse();
            botoesInvisivel();
        }
    }//GEN-LAST:event_jB_turma5ActionPerformed

    private void jB_alunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_alunoActionPerformed

        // TODO add your handling code here:
        if (statusjB_aluno == false) {
            botoesInvisivel();
            statusFalse();
            statusjB_aluno = true;
            jB_addAluno.setVisible(true);
            jB_editAluno.setVisible(true);
            jB_listAluno.setVisible(true);
        } else {
            statusFalse();
            botoesInvisivel();
        }
    }//GEN-LAST:event_jB_alunoActionPerformed

    private void jB_addCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_addCursoActionPerformed
        // TODO add your handling code here:
        JFrameCadastrarCurso frame = new JFrameCadastrarCurso();
        frame.setVisible(true);
    }//GEN-LAST:event_jB_addCursoActionPerformed

    private void jB_editCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editCursoActionPerformed
        // TODO add your handling code here:
        JFrameAlterarCurso frame = new JFrameAlterarCurso();
        frame.setVisible(true);
    }//GEN-LAST:event_jB_editCursoActionPerformed

    private void jB_addProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_addProfActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jB_addProfActionPerformed

    private void jB_editProfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editProfActionPerformed
        // TODO add your handling code here:
        JFrameAlterarProfessor frame = new JFrameAlterarProfessor();
        frame.setVisible(true);
    }//GEN-LAST:event_jB_editProfActionPerformed

    private void jB_addAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_addAlunoActionPerformed
        // TODO add your handling code here:
        JFrameCadastrarAluno frame = new JFrameCadastrarAluno();
        frame.setVisible(true);
    }//GEN-LAST:event_jB_addAlunoActionPerformed

    private void jB_editAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editAlunoActionPerformed
        // TODO add your handling code here:
        JFrameAlterarAluno frame = new JFrameAlterarAluno();
        frame.setVisible(true);
    }//GEN-LAST:event_jB_editAlunoActionPerformed

    private void jB_editAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editAdmActionPerformed
        // TODO add your handling code here:
        JFrameAlterarAdministrador frame = new JFrameAlterarAdministrador();
        frame.setVisible(true);
    }//GEN-LAST:event_jB_editAdmActionPerformed

    private void jB_addAdmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_addAdmActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jB_addAdmActionPerformed

    private void jB_editDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_editDiscActionPerformed

    private void jB_addDiscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_addDiscActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_addDiscActionPerformed

    private void jB_addTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_addTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_addTurmaActionPerformed

    private void jB_editTurmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_editTurmaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_editTurmaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_adm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame_adm().setVisible(true);

            }
        });
    }

    public void bemvindo() {
        try {
            model = controle.buscarAdministrador(user);
        } catch (SQLException ex) {
            Logger.getLogger(JFrame_adm.class.getName()).log(Level.SEVERE, null, ex);
        }
        String jL_nome = null;
        if (model != null) {
            jL_nome = model.getNome();
        }
        jL_bemvindoAluno.setText("Bem vindo " + jL_nome);
    }

    public void botoesInvisivel() {
        jB_addCurso.setVisible(false);
        jB_editCurso.setVisible(false);
        jB_listCurso.setVisible(false);
        jB_addProf.setVisible(false);
        jB_editProf.setVisible(false);
        jB_listProf.setVisible(false);
        jB_addAluno.setVisible(false);
        jB_editAluno.setVisible(false);
        jB_listAluno.setVisible(false);
        jB_addAdm.setVisible(false);
        jB_editAdm.setVisible(false);
        jB_listAdm.setVisible(false);
        jB_addDisc.setVisible(false);
        jB_editDisc.setVisible(false);
        jB_listDisc.setVisible(false);
        jB_addTurma.setVisible(false);
        jB_editTurma.setVisible(false);
        jB_listTurma.setVisible(false);
    }

    public void statusFalse() {
        statusjB_curso = false;
        statusjB_prof = false;
        statusjB_aluno = false;
        statusjB_disciplina = false;
        statusjB_turma = false;
        statusjB_adm = false;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_addAdm;
    private javax.swing.JButton jB_addAluno;
    private javax.swing.JButton jB_addCurso;
    private javax.swing.JButton jB_addDisc;
    private javax.swing.JButton jB_addProf;
    private javax.swing.JButton jB_addTurma;
    private javax.swing.JButton jB_aluno;
    private javax.swing.JButton jB_curso;
    private javax.swing.JButton jB_editAdm;
    private javax.swing.JButton jB_editAluno;
    private javax.swing.JButton jB_editCurso;
    private javax.swing.JButton jB_editDisc;
    private javax.swing.JButton jB_editProf;
    private javax.swing.JButton jB_editTurma;
    private javax.swing.JButton jB_listAdm;
    private javax.swing.JButton jB_listAluno;
    private javax.swing.JButton jB_listCurso;
    private javax.swing.JButton jB_listDisc;
    private javax.swing.JButton jB_listProf;
    private javax.swing.JButton jB_listTurma;
    private javax.swing.JButton jB_prof;
    private javax.swing.JButton jB_turma3;
    private javax.swing.JButton jB_turma4;
    private javax.swing.JButton jB_turma5;
    private javax.swing.JLabel jL_bemvindoAluno;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
