/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.Curso;
import Controle.CursoDAO;
import Controle.DisciplinaDAO;
import Modelo.Disciplina;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anderson
 */
public class JFrameAlterarDisciplina extends javax.swing.JFrame {
    Disciplina model = new Disciplina();
    DisciplinaDAO control = new DisciplinaDAO();
    int buscou=0;
    int codigoCursoMudado=-1;
    /**
     * Creates new form cadastrarCurso
     */
    public JFrameAlterarDisciplina() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }
    
    public void invisivel(){
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jT_codigocursoAlterarDisciplina = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_nomedisciplinaAlterarDisciplina = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jB_cancelarAlterarCurso = new javax.swing.JButton();
        jB_buscarAlterarDisciplina = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jT_creditosAlterarDisciplina = new javax.swing.JTextField();
        jT_buscarAlterarDisciplina = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jB_confirmarAlterarDisciplina = new javax.swing.JButton();
        jT_descricaoAlterarDisciplina = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jT_statusAlterarDisciplina = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBuscaDisciplina = new javax.swing.JTable();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 44, 68));
        jLabel2.setText("Código do Curso");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 330, 110, 27);

        jT_codigocursoAlterarDisciplina.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_codigocursoAlterarDisciplina.setForeground(new java.awt.Color(36, 44, 68));
        jT_codigocursoAlterarDisciplina.setText(" ");
        jT_codigocursoAlterarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_codigocursoAlterarDisciplinaActionPerformed(evt);
            }
        });
        getContentPane().add(jT_codigocursoAlterarDisciplina);
        jT_codigocursoAlterarDisciplina.setBounds(20, 360, 349, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/curso.fw.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(230, 10, 32, 32);

        jLabel1.setBackground(new java.awt.Color(36, 44, 68));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alterar dados da Disciplina");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 708, 57);

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 44, 68));
        jLabel3.setText("Buscar Código da disciplina");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 220, 27);

        jT_nomedisciplinaAlterarDisciplina.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_nomedisciplinaAlterarDisciplina.setForeground(new java.awt.Color(36, 44, 68));
        jT_nomedisciplinaAlterarDisciplina.setText(" ");
        getContentPane().add(jT_nomedisciplinaAlterarDisciplina);
        jT_nomedisciplinaAlterarDisciplina.setBounds(20, 300, 340, 30);

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 44, 68));
        jLabel5.setText("Descrição");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 390, 90, 27);

        jB_cancelarAlterarCurso.setBackground(new java.awt.Color(255, 51, 51));
        jB_cancelarAlterarCurso.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_cancelarAlterarCurso.setForeground(new java.awt.Color(255, 255, 255));
        jB_cancelarAlterarCurso.setText("Cancelar");
        jB_cancelarAlterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarAlterarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jB_cancelarAlterarCurso);
        jB_cancelarAlterarCurso.setBounds(330, 480, 110, 33);

        jB_buscarAlterarDisciplina.setBackground(new java.awt.Color(0, 204, 51));
        jB_buscarAlterarDisciplina.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_buscarAlterarDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        jB_buscarAlterarDisciplina.setText("Buscar");
        jB_buscarAlterarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarAlterarDisciplinaActionPerformed(evt);
            }
        });
        getContentPane().add(jB_buscarAlterarDisciplina);
        jB_buscarAlterarDisciplina.setBounds(160, 100, 110, 33);

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 44, 68));
        jLabel7.setText("Creditos");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(480, 270, 60, 27);

        jT_creditosAlterarDisciplina.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_creditosAlterarDisciplina.setForeground(new java.awt.Color(36, 44, 68));
        jT_creditosAlterarDisciplina.setText(" ");
        getContentPane().add(jT_creditosAlterarDisciplina);
        jT_creditosAlterarDisciplina.setBounds(460, 300, 100, 30);

        jT_buscarAlterarDisciplina.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_buscarAlterarDisciplina.setForeground(new java.awt.Color(36, 44, 68));
        jT_buscarAlterarDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_buscarAlterarDisciplinaKeyReleased(evt);
            }
        });
        getContentPane().add(jT_buscarAlterarDisciplina);
        jT_buscarAlterarDisciplina.setBounds(20, 100, 100, 30);

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 44, 68));
        jLabel9.setText("Nome da Disciplina");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 270, 160, 27);

        jB_confirmarAlterarDisciplina.setBackground(new java.awt.Color(0, 204, 51));
        jB_confirmarAlterarDisciplina.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_confirmarAlterarDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        jB_confirmarAlterarDisciplina.setText("Confirmar");
        jB_confirmarAlterarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_confirmarAlterarDisciplinaActionPerformed(evt);
            }
        });
        getContentPane().add(jB_confirmarAlterarDisciplina);
        jB_confirmarAlterarDisciplina.setBounds(460, 480, 110, 33);

        jT_descricaoAlterarDisciplina.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_descricaoAlterarDisciplina.setForeground(new java.awt.Color(36, 44, 68));
        jT_descricaoAlterarDisciplina.setText(" ");
        jT_descricaoAlterarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_descricaoAlterarDisciplinaActionPerformed(evt);
            }
        });
        getContentPane().add(jT_descricaoAlterarDisciplina);
        jT_descricaoAlterarDisciplina.setBounds(20, 420, 349, 30);

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 44, 68));
        jLabel8.setText("Status");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(480, 340, 60, 27);

        jT_statusAlterarDisciplina.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_statusAlterarDisciplina.setForeground(new java.awt.Color(36, 44, 68));
        jT_statusAlterarDisciplina.setText(" ");
        getContentPane().add(jT_statusAlterarDisciplina);
        jT_statusAlterarDisciplina.setBounds(460, 370, 100, 30);

        jTableBuscaDisciplina.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Nome", "Codigo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBuscaDisciplina.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBuscaDisciplinaMouseClicked(evt);
            }
        });
        jTableBuscaDisciplina.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableBuscaDisciplinaKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBuscaDisciplina);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 140, 450, 110);

        setSize(new java.awt.Dimension(618, 580));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_cancelarAlterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarAlterarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_cancelarAlterarCursoActionPerformed

    private void jB_buscarAlterarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarAlterarDisciplinaActionPerformed
         if(!(jT_buscarAlterarDisciplina.getText().equals(""))){
             int codDisciplina =(Integer.parseInt(jT_buscarAlterarDisciplina.getText()));
             try {
                 model = control.buscarDisciplina(codDisciplina);
                    if(model!=null){
                        jT_creditosAlterarDisciplina.setText(String.valueOf(model.getCredito()));
                        jT_descricaoAlterarDisciplina.setText(model.getDescricao());
                        jT_codigocursoAlterarDisciplina.setText(String.valueOf(model.getCurso().getCodCurso()));
                        jT_nomedisciplinaAlterarDisciplina.setText(String.valueOf(model.getNomeDisc()));
                        codigoCursoMudado=model.getCurso().getCodCurso();
                        buscou=1;
                    }else{
                        jT_creditosAlterarDisciplina.setText("");
                        jT_descricaoAlterarDisciplina.setText("");
                        jT_codigocursoAlterarDisciplina.setText("");
                        jT_nomedisciplinaAlterarDisciplina.setText("");
                        jT_buscarAlterarDisciplina.setText("");
                        codigoCursoMudado=-1;
                        buscou=0;
                        JOptionPane.showMessageDialog(null, "Esta disciplina não existe!");
                    }
             } catch (SQLException ex) {
                 Logger.getLogger(JFrameAlterarDisciplina.class.getName()).log(Level.SEVERE, null, ex);
             }
        }else{
            JOptionPane.showMessageDialog(null, "Insira algum número no campo para buscar uma disciplina");
            jT_creditosAlterarDisciplina.setText("");
            jT_descricaoAlterarDisciplina.setText("");
            jT_codigocursoAlterarDisciplina.setText("");
            jT_nomedisciplinaAlterarDisciplina.setText("");
            jT_buscarAlterarDisciplina.setText("");
            buscou=0;
         }
    }//GEN-LAST:event_jB_buscarAlterarDisciplinaActionPerformed

    private void jB_confirmarAlterarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_confirmarAlterarDisciplinaActionPerformed
        if(buscou==1){
            /*}else if(model.getUniversidadeCod()!=(Integer.parseInt(jT_universidadeAlterarCurso.getText()))){
                    JOptionPane.showMessageDialog(null,"Número da universidade não pode ser alterado!");*/
                if((jT_codigocursoAlterarDisciplina.getText().equals(""))||(jT_creditosAlterarDisciplina.getText().equals(""))||(jT_descricaoAlterarDisciplina.getText().equals(""))||(jT_nomedisciplinaAlterarDisciplina.getText().equals("")))
                {
                    JOptionPane.showMessageDialog(null,"Todos os campos devem ser preenchidos!");
                }else{
                    Curso modelVerifica = new Curso();
                    CursoDAO controlVerifica = new CursoDAO();
                        if(codigoCursoMudado!=Integer.parseInt(jT_codigocursoAlterarDisciplina.getText())){
                            try {
                                modelVerifica = controlVerifica.buscarCurso(Integer.parseInt(jT_codigocursoAlterarDisciplina.getText()));
                            } catch (SQLException ex) {
                                Logger.getLogger(JFrameAlterarDisciplina.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    if(modelVerifica!=null){
                        try {
                            model.setCredito((Integer.parseInt(jT_creditosAlterarDisciplina.getText())));
                            model.getCurso().setCodCurso((Integer.parseInt(jT_codigocursoAlterarDisciplina.getText())));
                            model.setDescricao(jT_descricaoAlterarDisciplina.getText());
                            model.setNomeDisc(jT_nomedisciplinaAlterarDisciplina.getText());
                            control.alterarDisciplina(model);
                            JOptionPane.showMessageDialog(null,"Disciplina alterada com sucesso!");
                            jT_creditosAlterarDisciplina.setText("");
                            jT_descricaoAlterarDisciplina.setText("");
                            jT_codigocursoAlterarDisciplina.setText("");
                            jT_nomedisciplinaAlterarDisciplina.setText("");
                            jT_buscarAlterarDisciplina.setText("");
                            buscou=0;
                        } catch (SQLException ex) {
                            Logger.getLogger(JFrameAlterarDisciplina.class.getName()).log(Level.SEVERE, null, ex);
                        }
                    }else{
                        JOptionPane.showMessageDialog(null,"O código do curso o qual você digitou, não existe!");
                        codigoCursoMudado=-1;
                    }
                }
        }else{
            JOptionPane.showMessageDialog(null, "Você deve buscar uma disciplina primeiro!");
            jT_creditosAlterarDisciplina.setText("");
            jT_descricaoAlterarDisciplina.setText("");
            jT_codigocursoAlterarDisciplina.setText("");
            jT_nomedisciplinaAlterarDisciplina.setText("");
            jT_buscarAlterarDisciplina.setText("");
            codigoCursoMudado=-1;
            buscou=0;
        }
    }//GEN-LAST:event_jB_confirmarAlterarDisciplinaActionPerformed

    private void jT_codigocursoAlterarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_codigocursoAlterarDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_codigocursoAlterarDisciplinaActionPerformed

    private void jT_descricaoAlterarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_descricaoAlterarDisciplinaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_descricaoAlterarDisciplinaActionPerformed

    private void jTableBuscaDisciplinaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBuscaDisciplinaMouseClicked
        int linha = jTableBuscaDisciplina.getSelectedRow();
        model=null;
        try {
            model = control.buscarDisciplina(Integer.parseInt(jTableBuscaDisciplina.getValueAt(linha,1).toString()));
//            System.out.println(model);
        } catch (SQLException ex) {
            Logger.getLogger(JFrameAlterarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(model!=null){
            try {
                model=null;
                model = control.buscarDisciplina(Integer.parseInt(jTableBuscaDisciplina.getValueAt(linha,1).toString()));
                //jT_nomealunoAlterarAluno.setText(jTableBuscaAluno.getValueAt(linha,0).toString());
                jT_creditosAlterarDisciplina.setText(String.valueOf(model.getCredito()));
                jT_descricaoAlterarDisciplina.setText(model.getDescricao());
                jT_codigocursoAlterarDisciplina.setText(String.valueOf(model.getCurso().getCodCurso()));
                jT_nomedisciplinaAlterarDisciplina.setText(String.valueOf(model.getNomeDisc()));
                jT_statusAlterarDisciplina.setText(String.valueOf(model.getStatus()));
                codigoCursoMudado=model.getCurso().getCodCurso();
                buscou=1;
            } catch (SQLException ex) {
                Logger.getLogger(JFrameAlterarAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTableBuscaDisciplinaMouseClicked

    private void jTableBuscaDisciplinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableBuscaDisciplinaKeyReleased

    }//GEN-LAST:event_jTableBuscaDisciplinaKeyReleased

    private void jT_buscarAlterarDisciplinaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_buscarAlterarDisciplinaKeyReleased
        Vector cabecalho = new  Vector();
        cabecalho.add("Nome");
        cabecalho.add("Codigo");
        if(!jT_buscarAlterarDisciplina.getText().equals("")){
            try {
                DefaultTableModel nv = new DefaultTableModel(control.Pesquisar(jT_buscarAlterarDisciplina.getText()),cabecalho);
                jTableBuscaDisciplina.setModel(nv);
            } catch (Exception ex) {
                Logger.getLogger(JFrameAlterarAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
       }else{
            jT_creditosAlterarDisciplina.setText("");
            jT_descricaoAlterarDisciplina.setText("");
            jT_codigocursoAlterarDisciplina.setText("");
            jT_nomedisciplinaAlterarDisciplina.setText("");
            jT_buscarAlterarDisciplina.setText("");
            DefaultTableModel nv = new DefaultTableModel(new Vector(),cabecalho);
            jTableBuscaDisciplina.setModel(nv);
        }
        
    }//GEN-LAST:event_jT_buscarAlterarDisciplinaKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAlterarDisciplina().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_buscarAlterarDisciplina;
    private javax.swing.JButton jB_cancelarAlterarCurso;
    private javax.swing.JButton jB_confirmarAlterarDisciplina;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jT_buscarAlterarDisciplina;
    private javax.swing.JTextField jT_codigocursoAlterarDisciplina;
    private javax.swing.JTextField jT_creditosAlterarDisciplina;
    private javax.swing.JTextField jT_descricaoAlterarDisciplina;
    private javax.swing.JTextField jT_nomedisciplinaAlterarDisciplina;
    private javax.swing.JTextField jT_statusAlterarDisciplina;
    private javax.swing.JTable jTableBuscaDisciplina;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
