/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.AlunoDAO;
import Controle.CursoDAO;
import Modelo.Aluno;
import Modelo.Curso;
import java.sql.Date;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author laercio
 */
public class JFrameCadastrarAluno extends javax.swing.JFrame{
    
    Aluno model = new Aluno();
    AlunoDAO controle = new AlunoDAO(); 
 
    
    public JFrameCadastrarAluno() {
        initComponents();
        this.setLocationRelativeTo(null);
        //popularUF();
        popularStatus();
        
    }

    //Esse método preenche o JCombobox de UF de Cadastro de Aluno;
    private void popularUF(){
        jComboBox_ufUsuario.removeAllItems();
        ArrayList<Aluno> listaDeUF = new ArrayList();
        
        try {
            listaDeUF = controle.visualizarAlunos();
            Iterator it = listaDeUF.iterator();
            for (Aluno uf : listaDeUF) {
                jComboBox_ufUsuario.addItem(uf.getUf());
                System.out.println("steste"+uf.getUf());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error ao listar combobox!");
        }
    }         
    
    //Esse método preenche o JCombobox de UF de Cadastro de Aluno;
    private void popularStatus(){
        jComboBox_statusCadAluno.removeAllItems();
        ArrayList<Aluno> listaDeStatus = new ArrayList();
        
        try {
            listaDeStatus = controle.visualizarAlunos();
            Iterator it = listaDeStatus.iterator();
            for (Aluno s : listaDeStatus) {
                jComboBox_statusCadAluno.addItem(s.getStatus());
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Error ao listar combobox!");
        }
    }            
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField_matriculaCadAluno = new javax.swing.JTextField();
        jTextField_nomeCadAluno = new javax.swing.JTextField();
        jTextField_ruaCadAluno = new javax.swing.JTextField();
        jComboBox_ufUsuario = new javax.swing.JComboBox<Object>();
        jComboBox_statusCadAluno = new javax.swing.JComboBox<Object>();
        jTextField_emailCadAluno = new javax.swing.JTextField();
        jB_cancelarCadAluno = new javax.swing.JButton();
        jB_cadastrarAluno = new javax.swing.JButton();
        jT_cursoCadAluno = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jT_cidadeCadAluno = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jF_dataNascCadAluno = new javax.swing.JFormattedTextField();
        jLabel19 = new javax.swing.JLabel();
        jT_foneCadAluno = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jT_cepCadAluno = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jT_anoIngressoCadAluno = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jT_craCadAluno = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jT_tabelaCursos = new javax.swing.JTable();

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 44, 68));
        jLabel10.setText("Matrícula");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel14.setBackground(new java.awt.Color(36, 44, 68));
        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cadastrar Aluno");
        jLabel14.setOpaque(true);

        jTextField_matriculaCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_matriculaCadAlunoActionPerformed(evt);
            }
        });

        jB_cancelarCadAluno.setBackground(new java.awt.Color(255, 51, 51));
        jB_cancelarCadAluno.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_cancelarCadAluno.setForeground(new java.awt.Color(255, 255, 255));
        jB_cancelarCadAluno.setText("Cancelar");
        jB_cancelarCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarCadAlunoActionPerformed(evt);
            }
        });

        jB_cadastrarAluno.setBackground(new java.awt.Color(0, 204, 51));
        jB_cadastrarAluno.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_cadastrarAluno.setForeground(new java.awt.Color(255, 255, 255));
        jB_cadastrarAluno.setText("Cadastrar");
        jB_cadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cadastrarAlunoActionPerformed(evt);
            }
        });

        jT_cursoCadAluno.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_cursoCadAlunoKeyReleased(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 44, 68));
        jLabel11.setText("CEP");

        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(36, 44, 68));
        jLabel12.setText("Matrícula");

        jLabel13.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(36, 44, 68));
        jLabel13.setText("Nome");

        jLabel15.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(36, 44, 68));
        jLabel15.setText("e-mail");

        jLabel16.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(36, 44, 68));
        jLabel16.setText("Rua");

        jLabel17.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(36, 44, 68));
        jLabel17.setText("Cidade");

        jLabel18.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(36, 44, 68));
        jLabel18.setText("Curso");

        jLabel19.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(36, 44, 68));
        jLabel19.setText("Data de Nascimento");

        jLabel20.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(36, 44, 68));
        jLabel20.setText("Telefone");

        jLabel21.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(36, 44, 68));
        jLabel21.setText("Cra");

        jLabel22.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(36, 44, 68));
        jLabel22.setText("Ano de Ingresso");

        jLabel23.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(36, 44, 68));
        jLabel23.setText("Status");

        jLabel24.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(36, 44, 68));
        jLabel24.setText("UF");

        jT_tabelaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Nome do Curso", "Código"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_tabelaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jT_tabelaCursosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jT_tabelaCursos);
        if (jT_tabelaCursos.getColumnModel().getColumnCount() > 0) {
            jT_tabelaCursos.getColumnModel().getColumn(0).setMinWidth(80);
            jT_tabelaCursos.getColumnModel().getColumn(0).setMaxWidth(80);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jTextField_matriculaCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(jLabel13)
                        .addComponent(jLabel16)
                        .addComponent(jLabel17)
                        .addComponent(jTextField_nomeCadAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                        .addComponent(jT_cidadeCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField_emailCadAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                        .addComponent(jTextField_ruaCadAluno))
                    .addComponent(jLabel11)
                    .addComponent(jT_cepCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(146, 146, 146)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jT_foneCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(363, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jB_cancelarCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jB_cadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel22)
                                    .addComponent(jT_anoIngressoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel19)
                                    .addComponent(jF_dataNascCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel20)
                                    .addComponent(jT_cursoCadAluno, javax.swing.GroupLayout.DEFAULT_SIZE, 277, Short.MAX_VALUE)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                                .addGap(158, 158, 158)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel23)
                                    .addComponent(jComboBox_ufUsuario, 0, 105, Short.MAX_VALUE)
                                    .addComponent(jComboBox_statusCadAluno, 0, 105, Short.MAX_VALUE)
                                    .addComponent(jLabel21)
                                    .addComponent(jT_craCadAluno)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addGap(373, 373, 373)
                                .addComponent(jLabel24)))
                        .addGap(0, 53, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(jLabel18))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_cursoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(jComboBox_ufUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(560, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_matriculaCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jT_anoIngressoCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addGap(21, 21, 21)
                                .addComponent(jF_dataNascCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel20)
                                .addGap(18, 18, 18)
                                .addComponent(jT_foneCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(88, 88, 88)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jB_cadastrarAluno, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jB_cancelarCadAluno))
                                .addGap(52, 52, 52))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_nomeCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextField_ruaCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel17)
                                        .addGap(18, 18, 18)
                                        .addComponent(jT_cidadeCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jT_cepCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(jLabel23)
                                        .addGap(18, 18, 18)
                                        .addComponent(jComboBox_statusCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(63, 63, 63)
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jT_craCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(29, 29, 29)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_emailCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_cancelarCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarCadAlunoActionPerformed
        Object[] options = { "Sim", "Não" };
        int opcao = JOptionPane.showOptionDialog(null, "Deseja realmente cancelar o cadastro?", "Cancelar Cadastro", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE , null, options, options[0]);
        System.out.println("opcao "+opcao);
        
        if(opcao==0){
            dispose();
            System.exit(0);
            //setDefaultCloseOperation(JFrameCadastrarAluno.DISPOSE_ON_CLOSE);
        }else{}
    }//GEN-LAST:event_jB_cancelarCadAlunoActionPerformed

    /**
     *Converte uma String para um objeto do tipo Date;
     * @param dateInput
     * @param date
     * @return
     */
    public Date FormatDate(String dateInput){

        SimpleDateFormat formatDate = new SimpleDateFormat("dd/MM/yyyy");
        Date dateOutput = null;
        try {
            dateOutput = (Date) formatDate.parse(dateInput);
        } catch (ParseException ex) {
            ex.printStackTrace();
        }
        
       return dateOutput;  
    }
    
    private void jB_cadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cadastrarAlunoActionPerformed

            //Validação dos campos quando vazios!
          if((jTextField_matriculaCadAluno.getText().trim().isEmpty() ||  jTextField_nomeCadAluno.getText().trim().equals("") || 
              jTextField_ruaCadAluno.getText().trim().equals("") ||
              jT_cidadeCadAluno.getText().trim().equals(" ") || jTextField_emailCadAluno.getText().trim().equals("") ||
              jT_anoIngressoCadAluno.getText().trim().equals("") || jT_cursoCadAluno.getText().trim().isEmpty() ||
              jF_dataNascCadAluno.getText().trim().equals("") || jT_foneCadAluno.getText().trim().equals("")) ||
              jT_cepCadAluno.getText().trim().equals("") || jT_craCadAluno.getText().trim().equals("")||
              jComboBox_ufUsuario.getSelectedItem().toString().equals("")|| jComboBox_statusCadAluno.getSelectedItem().toString().equals("")
            ){
               JOptionPane.showMessageDialog(null, "Todos os campos tem que está preenchidos!");
           }else{
           
           
           model.setMatricula(Integer.parseInt(jTextField_matriculaCadAluno.getText()));
           model.setNome(jTextField_nomeCadAluno.getText());
           model.setRua(jTextField_ruaCadAluno.getText());
           model.setCidade(jT_cidadeCadAluno.getText());
           model.setEmail(jTextField_emailCadAluno.getText());
           model.setAnoIngressante(jT_anoIngressoCadAluno.getText());
           model.getCurso().setCodCurso(Integer.parseInt(jT_cursoCadAluno.getText())); //Falta Implementar o autocomplete.
           model.setDataNascimento(FormatDate(jF_dataNascCadAluno.getText()));
           model.setTelefone(jT_foneCadAluno.getText());
           model.setCep(jT_cepCadAluno.getText());
           model.setCra(Float.parseFloat(jT_craCadAluno.getText()));
           model.setUf((String) jComboBox_ufUsuario.getSelectedItem());
           model.setStatus((boolean) jComboBox_statusCadAluno.getSelectedItem());
           
            
              try {
                  controle.cadastrarAluno(model,1,model.getNome());
                  JOptionPane.showMessageDialog(null, "Novo usuario cadastrado com sucesso!");
              } catch (SQLException ex) {
                  Logger.getLogger(JFrameCadastrarAluno.class.getName()).log(Level.SEVERE, null, ex);
              }
         }

    }//GEN-LAST:event_jB_cadastrarAlunoActionPerformed

    private void jTextField_matriculaCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_matriculaCadAlunoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_matriculaCadAlunoActionPerformed

    private void jT_cursoCadAlunoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_cursoCadAlunoKeyReleased
        Vector cabecalho = new  Vector();
        cabecalho.add("Nome");
        cabecalho.add("Codigo");
        CursoDAO control= new CursoDAO();
        if(!jT_cursoCadAluno.getText().equals("")){
            try {
                DefaultTableModel nv = new DefaultTableModel(control.Pesquisar(jT_cursoCadAluno.getText()),cabecalho);
                jT_tabelaCursos.setModel(nv);
            } catch (Exception ex) {
                Logger.getLogger(JFrameAlterarAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
       }else{
            
            DefaultTableModel nv = new DefaultTableModel(new Vector(),cabecalho);
            jT_tabelaCursos.setModel(nv);
        }
    
    }//GEN-LAST:event_jT_cursoCadAlunoKeyReleased

    private void jT_tabelaCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jT_tabelaCursosMouseClicked
       int linha = jT_tabelaCursos.getSelectedRow();
        Curso modelCurso = new Curso();
        CursoDAO control = new CursoDAO();
        try {
            modelCurso = control.buscarCurso(Integer.parseInt(jT_tabelaCursos.getValueAt(linha,1).toString()));
        } catch (SQLException ex) {
            Logger.getLogger(JFrameAlterarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(modelCurso!=null){
            int codigoSelecionado = modelCurso.getCodCurso();
            System.out.println(codigoSelecionado);
        }
        
    }//GEN-LAST:event_jT_tabelaCursosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarAluno.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameCadastrarAluno().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_cadastrarAluno;
    private javax.swing.JButton jB_cancelarCadAluno;
    private javax.swing.JComboBox<Object> jComboBox_statusCadAluno;
    private javax.swing.JComboBox<Object> jComboBox_ufUsuario;
    private javax.swing.JFormattedTextField jF_dataNascCadAluno;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_anoIngressoCadAluno;
    private javax.swing.JTextField jT_cepCadAluno;
    private javax.swing.JTextField jT_cidadeCadAluno;
    private javax.swing.JTextField jT_craCadAluno;
    private javax.swing.JTextField jT_cursoCadAluno;
    private javax.swing.JTextField jT_foneCadAluno;
    private javax.swing.JTable jT_tabelaCursos;
    private javax.swing.JTextField jTextField_emailCadAluno;
    private javax.swing.JTextField jTextField_matriculaCadAluno;
    private javax.swing.JTextField jTextField_nomeCadAluno;
    private javax.swing.JTextField jTextField_ruaCadAluno;
    // End of variables declaration//GEN-END:variables

    
}
