package Visao;

import Controle.AdmDAO;
import Controle.AlunoDAO;
import Modelo.Curso;
import Controle.CursoDAO;
import Controle.DisciplinaDAO;
import Controle.ProfessorDAO;
import Modelo.Administrador;
import Modelo.Aluno;
import Modelo.Disciplina;
import Modelo.Professor;
import java.awt.Color;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import java.util.Date;

public class JFrameAlterarAdministrador extends javax.swing.JFrame {
    Administrador model = new Administrador();
    AdmDAO controle = new AdmDAO();
    int buscou=0;
    int codigoCursoMudado=-1;

    public JFrameAlterarAdministrador() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }
    
    public void invisivel(){
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_nomeadministradorAlterarAdministrador = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jB_cancelarAlterarCurso = new javax.swing.JButton();
        jB_buscarAlterarDisciplina = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jT_cidadeAlterarAdministrador = new javax.swing.JTextField();
        jT_buscarAlterarAdministador = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jB_confirmarAlterarProfessor = new javax.swing.JButton();
        jT_senhaAlterarAdministrador = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jT_cpfAlterarAdministrador = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jT_nascimentoAlterarAdministrador = new javax.swing.JTextField();
        jT_ufAlterarAdministrador = new javax.swing.JTextField();
        jT_bairroAlterarAdministrador = new javax.swing.JTextField();
        jT_cepAlterarAdministrador = new javax.swing.JTextField();
        jT_telefoneAlterarAdministrador = new javax.swing.JTextField();
        jT_emailAlterarAdministrador = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jT_ruaAlterarAdministrador = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jT_statusAlterarAdministrador = new javax.swing.JTextField();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/curso.fw.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(200, 10, 32, 32);

        jLabel1.setBackground(new java.awt.Color(36, 44, 68));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alterar dados do Administrador");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 708, 57);

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 44, 68));
        jLabel3.setText("Buscar Código Administrador");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 220, 27);

        jT_nomeadministradorAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_nomeadministradorAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        jT_nomeadministradorAlterarAdministrador.setText(" ");
        getContentPane().add(jT_nomeadministradorAlterarAdministrador);
        jT_nomeadministradorAlterarAdministrador.setBounds(20, 160, 280, 30);

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 44, 68));
        jLabel5.setText("Data de nascimento");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 340, 150, 20);

        jB_cancelarAlterarCurso.setBackground(new java.awt.Color(255, 51, 51));
        jB_cancelarAlterarCurso.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_cancelarAlterarCurso.setForeground(new java.awt.Color(255, 255, 255));
        jB_cancelarAlterarCurso.setText("Cancelar");
        jB_cancelarAlterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarAlterarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jB_cancelarAlterarCurso);
        jB_cancelarAlterarCurso.setBounds(340, 400, 110, 33);

        jB_buscarAlterarDisciplina.setBackground(new java.awt.Color(0, 204, 51));
        jB_buscarAlterarDisciplina.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_buscarAlterarDisciplina.setForeground(new java.awt.Color(255, 255, 255));
        jB_buscarAlterarDisciplina.setText("Buscar");
        jB_buscarAlterarDisciplina.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarAlterarDisciplinaActionPerformed(evt);
            }
        });
        getContentPane().add(jB_buscarAlterarDisciplina);
        jB_buscarAlterarDisciplina.setBounds(160, 100, 110, 33);

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 44, 68));
        jLabel7.setText("Email");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 390, 60, 20);

        jT_cidadeAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_cidadeAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        jT_cidadeAlterarAdministrador.setText(" ");
        getContentPane().add(jT_cidadeAlterarAdministrador);
        jT_cidadeAlterarAdministrador.setBounds(390, 120, 180, 30);

        jT_buscarAlterarAdministador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_buscarAlterarAdministador.setForeground(new java.awt.Color(36, 44, 68));
        getContentPane().add(jT_buscarAlterarAdministador);
        jT_buscarAlterarAdministador.setBounds(20, 100, 120, 30);

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 44, 68));
        jLabel9.setText("Nome do Administrador");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 140, 160, 20);

        jB_confirmarAlterarProfessor.setBackground(new java.awt.Color(0, 204, 51));
        jB_confirmarAlterarProfessor.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_confirmarAlterarProfessor.setForeground(new java.awt.Color(255, 255, 255));
        jB_confirmarAlterarProfessor.setText("Confirmar");
        jB_confirmarAlterarProfessor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_confirmarAlterarProfessorActionPerformed(evt);
            }
        });
        getContentPane().add(jB_confirmarAlterarProfessor);
        jB_confirmarAlterarProfessor.setBounds(470, 400, 110, 33);

        jT_senhaAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_senhaAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        jT_senhaAlterarAdministrador.setText(" ");
        jT_senhaAlterarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_senhaAlterarAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(jT_senhaAlterarAdministrador);
        jT_senhaAlterarAdministrador.setBounds(20, 260, 180, 30);

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 44, 68));
        jLabel6.setText("Senha");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 240, 90, 20);

        jT_cpfAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_cpfAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        jT_cpfAlterarAdministrador.setText(" ");
        jT_cpfAlterarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_cpfAlterarAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(jT_cpfAlterarAdministrador);
        jT_cpfAlterarAdministrador.setBounds(20, 310, 180, 30);

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 44, 68));
        jLabel8.setText("CPF");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(20, 290, 90, 20);

        jT_nascimentoAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_nascimentoAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        jT_nascimentoAlterarAdministrador.setText(" ");
        getContentPane().add(jT_nascimentoAlterarAdministrador);
        jT_nascimentoAlterarAdministrador.setBounds(20, 360, 180, 30);

        jT_ufAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_ufAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        getContentPane().add(jT_ufAlterarAdministrador);
        jT_ufAlterarAdministrador.setBounds(390, 170, 180, 30);

        jT_bairroAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_bairroAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        jT_bairroAlterarAdministrador.setText(" ");
        getContentPane().add(jT_bairroAlterarAdministrador);
        jT_bairroAlterarAdministrador.setBounds(390, 270, 180, 30);

        jT_cepAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_cepAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        jT_cepAlterarAdministrador.setText(" ");
        getContentPane().add(jT_cepAlterarAdministrador);
        jT_cepAlterarAdministrador.setBounds(390, 320, 180, 20);

        jT_telefoneAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_telefoneAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        jT_telefoneAlterarAdministrador.setText(" ");
        getContentPane().add(jT_telefoneAlterarAdministrador);
        jT_telefoneAlterarAdministrador.setBounds(390, 360, 180, 30);

        jT_emailAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_emailAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        jT_emailAlterarAdministrador.setText(" ");
        jT_emailAlterarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_emailAlterarAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(jT_emailAlterarAdministrador);
        jT_emailAlterarAdministrador.setBounds(20, 410, 180, 30);

        jLabel10.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(36, 44, 68));
        jLabel10.setText("Uf");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(390, 150, 60, 20);

        jLabel11.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 44, 68));
        jLabel11.setText("Rua");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(390, 200, 40, 20);

        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(36, 44, 68));
        jLabel12.setText("Bairro");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(390, 250, 60, 20);

        jLabel13.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(36, 44, 68));
        jLabel13.setText("Cep");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(390, 300, 60, 20);

        jLabel14.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(36, 44, 68));
        jLabel14.setText("Telefone");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(390, 340, 60, 20);

        jT_ruaAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_ruaAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        jT_ruaAlterarAdministrador.setText(" ");
        getContentPane().add(jT_ruaAlterarAdministrador);
        jT_ruaAlterarAdministrador.setBounds(390, 220, 180, 30);

        jLabel15.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(36, 44, 68));
        jLabel15.setText("Cidade");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(390, 100, 60, 20);

        jLabel16.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(36, 44, 68));
        jLabel16.setText("Status");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(20, 190, 60, 20);

        jT_statusAlterarAdministrador.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_statusAlterarAdministrador.setForeground(new java.awt.Color(36, 44, 68));
        jT_statusAlterarAdministrador.setText(" ");
        jT_statusAlterarAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_statusAlterarAdministradorActionPerformed(evt);
            }
        });
        getContentPane().add(jT_statusAlterarAdministrador);
        jT_statusAlterarAdministrador.setBounds(20, 210, 150, 30);

        setSize(new java.awt.Dimension(645, 545));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_cancelarAlterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarAlterarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_cancelarAlterarCursoActionPerformed

    private void jB_buscarAlterarDisciplinaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarAlterarDisciplinaActionPerformed
         if(!(jT_buscarAlterarAdministador.getText().equals(""))){
             int codadministrador =(Integer.parseInt(jT_buscarAlterarAdministador.getText()));
             try {
                 model = controle.buscarAdministrador(codadministrador);
                    if(model!=null){
                        jT_cidadeAlterarAdministrador.setText(String.valueOf(model.getCidade()));
                        jT_senhaAlterarAdministrador.setText(String.valueOf(model.getSenha()));
                        jT_nomeadministradorAlterarAdministrador.setText(String.valueOf(model.getNome()));
                        jT_bairroAlterarAdministrador.setText(model.getBairro());
                        jT_cepAlterarAdministrador.setText(model.getCep());
                        jT_cpfAlterarAdministrador.setText(model.getCpf());
                        jT_emailAlterarAdministrador.setText(model.getEmail());
                        jT_nascimentoAlterarAdministrador.setText(String.valueOf(model.getDataNascimento()));
                        jT_ruaAlterarAdministrador.setText(model.getRua());
                        jT_senhaAlterarAdministrador.setText(model.getSenha());
                        jT_statusAlterarAdministrador.setText(String.valueOf(model.getStatus()));
                        jT_telefoneAlterarAdministrador.setText(model.getTelefone());
                        jT_ufAlterarAdministrador.setText(model.getUf());
                        buscou=1;
                    }else{
                        jT_cidadeAlterarAdministrador.setText("");
                        jT_senhaAlterarAdministrador.setText("");
                        jT_nomeadministradorAlterarAdministrador.setText("");
                        jT_bairroAlterarAdministrador.setText("");
                        jT_cepAlterarAdministrador.setText("");
                        jT_cpfAlterarAdministrador.setText("");
                        jT_emailAlterarAdministrador.setText("");
                        jT_nascimentoAlterarAdministrador.setText("");
                        jT_ruaAlterarAdministrador.setText("");
                        jT_senhaAlterarAdministrador.setText("");
                        jT_telefoneAlterarAdministrador.setText("");
                        jT_ufAlterarAdministrador.setText("");
                        jT_statusAlterarAdministrador.setText("");
                        codigoCursoMudado=-1;
                        buscou=0;
                        JOptionPane.showMessageDialog(null, "Este Administrador não existe!");
                    }
             } catch (SQLException ex) {
                 Logger.getLogger(JFrameAlterarAdministrador.class.getName()).log(Level.SEVERE, null, ex);
             }
        }else{
            JOptionPane.showMessageDialog(null, "Insira algum número no campo para buscar um administrador");
            jT_cidadeAlterarAdministrador.setText("");
            jT_senhaAlterarAdministrador.setText("");
            jT_nomeadministradorAlterarAdministrador.setText("");
            jT_bairroAlterarAdministrador.setText("");
            jT_cepAlterarAdministrador.setText("");
            jT_cpfAlterarAdministrador.setText("");
            jT_emailAlterarAdministrador.setText("");
            jT_nascimentoAlterarAdministrador.setText("");
            jT_ruaAlterarAdministrador.setText("");
            jT_senhaAlterarAdministrador.setText("");
            jT_telefoneAlterarAdministrador.setText("");
            jT_ufAlterarAdministrador.setText("");
            jT_statusAlterarAdministrador.setText("");
            codigoCursoMudado=-1;
            buscou=0;
         }
    }//GEN-LAST:event_jB_buscarAlterarDisciplinaActionPerformed

    private void jB_confirmarAlterarProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_confirmarAlterarProfessorActionPerformed
        if(buscou==1){
            /*}else if(model.getUniversidadeCod()!=(Integer.parseInt(jT_universidadeAlterarCurso.getText()))){
                    JOptionPane.showMessageDialog(null,"Número da universidade não pode ser alterado!");*/
                if((jT_cidadeAlterarAdministrador.getText().equals(""))||(jT_senhaAlterarAdministrador.getText().equals(""))||(jT_nomeadministradorAlterarAdministrador.getText().equals(""))||jT_bairroAlterarAdministrador.getText().equals("")||jT_cepAlterarAdministrador.getText().equals("")||jT_cidadeAlterarAdministrador.getText().equals("")||jT_cpfAlterarAdministrador.getText().equals("")||jT_emailAlterarAdministrador.getText().equals("")||jT_nascimentoAlterarAdministrador.getText().equals("")||jT_nomeadministradorAlterarAdministrador.getText().equals("")||jT_ruaAlterarAdministrador.getText().equals("")||jT_senhaAlterarAdministrador.getText().equals("")||jT_telefoneAlterarAdministrador.getText().equals("")||jT_ufAlterarAdministrador.getText().equals(""))
                {   
                    JOptionPane.showMessageDialog(null,"Todos os campos devem ser preenchidos!");
                }else{
                            model.setCidade(jT_cidadeAlterarAdministrador.getText());
                            model.setSenha(jT_senhaAlterarAdministrador.getText());
                            model.setNome(jT_nomeadministradorAlterarAdministrador.getText());
                            model.setBairro(jT_bairroAlterarAdministrador.getText());
                            model.setCep(jT_cepAlterarAdministrador.getText());
                            model.setCpf(jT_cpfAlterarAdministrador.getText());
                            model.setEmail(jT_emailAlterarAdministrador.getText());
                            //SimpleDateFormat formatter = new SimpleDateFormat(jT_nascimentoAlterarProfessor.getText());
                            //model.setDataNascimento((java.sql.Date)formatter.parse(jT_nascimentoAlterarProfessor.getText()));
                            model.setRua(jT_ruaAlterarAdministrador.getText());
                            model.setStatus(Boolean.parseBoolean(jT_statusAlterarAdministrador.getText()));
                            model.setTelefone(jT_telefoneAlterarAdministrador.getText());
                            model.setUf(jT_ufAlterarAdministrador.getText());
                            codigoCursoMudado=-1;
                            buscou=0;
                                try {
                                    controle.alterarAdm(model,1,"");
                                } catch (SQLException ex) {
                                    Logger.getLogger(JFrameAlterarAdministrador.class.getName()).log(Level.SEVERE, null, ex);
                                }
                            JOptionPane.showMessageDialog(null,"Administrador alterado com sucesso!");
                            jT_cidadeAlterarAdministrador.setText("");
                            jT_senhaAlterarAdministrador.setText("");
                            jT_nomeadministradorAlterarAdministrador.setText("");
                            jT_bairroAlterarAdministrador.setText("");
                            jT_cepAlterarAdministrador.setText("");
                            jT_cpfAlterarAdministrador.setText("");
                            jT_emailAlterarAdministrador.setText("");
                            jT_nascimentoAlterarAdministrador.setText("");
                            jT_ruaAlterarAdministrador.setText("");
                            jT_senhaAlterarAdministrador.setText("");
                            jT_telefoneAlterarAdministrador.setText("");
                            jT_ufAlterarAdministrador.setText("");
                            jT_statusAlterarAdministrador.setText("");
                            buscou=0;   
                }
        }else{
            JOptionPane.showMessageDialog(null, "Você deve buscar um professor primeiro!");
            jT_cidadeAlterarAdministrador.setText("");
            jT_senhaAlterarAdministrador.setText("");
            jT_nomeadministradorAlterarAdministrador.setText("");
            jT_bairroAlterarAdministrador.setText("");
            jT_cepAlterarAdministrador.setText("");
            jT_cpfAlterarAdministrador.setText("");
            jT_emailAlterarAdministrador.setText("");
            jT_nascimentoAlterarAdministrador.setText("");
            jT_ruaAlterarAdministrador.setText("");
            jT_senhaAlterarAdministrador.setText("");
            jT_telefoneAlterarAdministrador.setText("");
            jT_ufAlterarAdministrador.setText("");
            jT_statusAlterarAdministrador.setText("");
           codigoCursoMudado=-1;
            buscou=0;
        }
    }//GEN-LAST:event_jB_confirmarAlterarProfessorActionPerformed

    private void jT_senhaAlterarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_senhaAlterarAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_senhaAlterarAdministradorActionPerformed

    private void jT_cpfAlterarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_cpfAlterarAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_cpfAlterarAdministradorActionPerformed

    private void jT_emailAlterarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_emailAlterarAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_emailAlterarAdministradorActionPerformed

    private void jT_statusAlterarAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_statusAlterarAdministradorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_statusAlterarAdministradorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAlterarAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_buscarAlterarDisciplina;
    private javax.swing.JButton jB_cancelarAlterarCurso;
    private javax.swing.JButton jB_confirmarAlterarProfessor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jT_bairroAlterarAdministrador;
    private javax.swing.JTextField jT_buscarAlterarAdministador;
    private javax.swing.JTextField jT_cepAlterarAdministrador;
    private javax.swing.JTextField jT_cidadeAlterarAdministrador;
    private javax.swing.JTextField jT_cpfAlterarAdministrador;
    private javax.swing.JTextField jT_emailAlterarAdministrador;
    private javax.swing.JTextField jT_nascimentoAlterarAdministrador;
    private javax.swing.JTextField jT_nomeadministradorAlterarAdministrador;
    private javax.swing.JTextField jT_ruaAlterarAdministrador;
    private javax.swing.JTextField jT_senhaAlterarAdministrador;
    private javax.swing.JTextField jT_statusAlterarAdministrador;
    private javax.swing.JTextField jT_telefoneAlterarAdministrador;
    private javax.swing.JTextField jT_ufAlterarAdministrador;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
