/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.DisciplinaDAO;
import Modelo.Disciplina;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anderson
 */
public class JFrameHistoricoAluno extends javax.swing.JFrame {
    Disciplina model = new Disciplina();
    DisciplinaDAO control = new DisciplinaDAO();
    private ArrayList<Disciplina> alDisciplina;
    private DefaultTableModel modeloTable;
    
    
    /**
     * Creates new form cadastrarCurso
     */
    public JFrameHistoricoAluno() {
        initComponents();
        getContentPane().setBackground(Color.white);
        
                
        //Lista de alunos.
        try{
            
            // faltam dados para o historico
            
            //this.alDisciplina = control.historicoAlunos();
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao carregar lista de alunos");
        }
        
        
        
        
    }
    
        
    private void configTable(){
        this.modeloTable = (DefaultTableModel) jTHistoricoAluno.getModel();
        //jTHistoricoAluno.getColumnModel().getColumn(0).setHeaderValue("codigo");
        //jTHistoricoAluno.getColumnModel().getColumn(1).setHeaderValue("Nome");
        jTHistoricoAluno.getTableHeader().setResizingAllowed(false);
        jTHistoricoAluno.getTableHeader().setReorderingAllowed(false);
        jTHistoricoAluno.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        //jTHistoricoAluno.isCellEditable(1, 1);
        
        try{
            //seta dados na tabela historico usando Interators
            alDisciplina.stream().forEach((disciplina) -> {
                modeloTable.addRow(new Object[] {
                
                // faltao dados da lista para historico
                
                });
            });
        }catch(Exception ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao listar Alunos");
        }
        
        jTHistoricoAluno.updateUI();
    }
    
    public void invisivel(){
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jBfecharHistoricoAluno = new javax.swing.JButton();
        jLNomeAluno = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        int linhas = 100, colunas = 5;
        jTHistoricoAluno = new javax.swing.JTable();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        getContentPane().setLayout(null);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/curso.fw.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(60, 10, 32, 32);

        jLabel1.setBackground(new java.awt.Color(36, 44, 68));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Histórico Aluno");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 708, 57);

        jBfecharHistoricoAluno.setBackground(new java.awt.Color(0, 204, 51));
        jBfecharHistoricoAluno.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jBfecharHistoricoAluno.setForeground(new java.awt.Color(255, 255, 255));
        jBfecharHistoricoAluno.setText("Fechar");
        jBfecharHistoricoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBfecharHistoricoAlunoActionPerformed(evt);
            }
        });
        getContentPane().add(jBfecharHistoricoAluno);
        jBfecharHistoricoAluno.setBounds(600, 270, 110, 34);

        jLNomeAluno.setText(" NOME DO ALUNO AQUI");
        getContentPane().add(jLNomeAluno);
        jLNomeAluno.setBounds(10, 70, 700, 30);

        jTHistoricoAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Codigo", "Disciplina", "1ª Nota", "2ª Nota", "3ª Nota"
            }
        ));
        jScrollPane2.setViewportView(jTHistoricoAluno);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(10, 110, 700, 150);

        setSize(new java.awt.Dimension(724, 345));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBfecharHistoricoAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBfecharHistoricoAlunoActionPerformed
        
          this.dispose();
    }//GEN-LAST:event_jBfecharHistoricoAlunoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame_cadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame_cadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame_cadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame_cadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new JFrameHistoricoAluno().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBfecharHistoricoAluno;
    private javax.swing.JLabel jLNomeAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTHistoricoAluno;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
