/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Modelo.Curso;
import Controle.CursoDAO;
import Controle.UniversidadeDAO;
import Modelo.Universidade;
import java.awt.Color;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anderson
 */
public class JFrameAlterarCurso extends javax.swing.JFrame {
    Curso model = new Curso();
    CursoDAO control = new CursoDAO();
    int buscou=0;
    int numUniversidade=0;
    /**
     * Creates new form cadastrarCurso
     */
    public JFrameAlterarCurso() {
        initComponents();
        getContentPane().setBackground(Color.white);
    }
    
    public void invisivel(){
        

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jLabel2 = new javax.swing.JLabel();
        jT_nomeAlterarCurso = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jT_universidadeAlterarCurso = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jT_statusAlterarCurso = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jB_cancelarAlterarCurso = new javax.swing.JButton();
        jB_buscarAlterarCurso = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jT_conceitoAlterarCurso = new javax.swing.JTextField();
        jT_buscarAlterarCurso = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jT_cargaAlterarCurso = new javax.swing.JTextField();
        jB_confirmarAlterarCurso1 = new javax.swing.JButton();
        jT_descricaoAlterarCurso = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableBuscaCurso = new javax.swing.JTable();

        jScrollPane1.setViewportView(jTextPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 0));
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(36, 44, 68));
        jLabel2.setText("Nome do Curso");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 330, 110, 27);

        jT_nomeAlterarCurso.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_nomeAlterarCurso.setForeground(new java.awt.Color(36, 44, 68));
        jT_nomeAlterarCurso.setText(" ");
        jT_nomeAlterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_nomeAlterarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jT_nomeAlterarCurso);
        jT_nomeAlterarCurso.setBounds(20, 360, 349, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/imagens/curso.fw.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 10, 32, 32);

        jLabel1.setBackground(new java.awt.Color(36, 44, 68));
        jLabel1.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Alterar dados do Curso");
        jLabel1.setOpaque(true);
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 620, 50);

        jLabel3.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(36, 44, 68));
        jLabel3.setText("Buscar nome do Curso");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 70, 170, 27);

        jT_universidadeAlterarCurso.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_universidadeAlterarCurso.setForeground(new java.awt.Color(36, 44, 68));
        jT_universidadeAlterarCurso.setText(" ");
        getContentPane().add(jT_universidadeAlterarCurso);
        jT_universidadeAlterarCurso.setBounds(20, 300, 340, 30);

        jLabel5.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(36, 44, 68));
        jLabel5.setText("Descrição");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 390, 90, 27);

        jT_statusAlterarCurso.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_statusAlterarCurso.setForeground(new java.awt.Color(36, 44, 68));
        jT_statusAlterarCurso.setText(" ");
        getContentPane().add(jT_statusAlterarCurso);
        jT_statusAlterarCurso.setBounds(450, 430, 100, 30);

        jLabel6.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(36, 44, 68));
        jLabel6.setText("Status");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(480, 400, 50, 27);

        jB_cancelarAlterarCurso.setBackground(new java.awt.Color(255, 51, 51));
        jB_cancelarAlterarCurso.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_cancelarAlterarCurso.setForeground(new java.awt.Color(255, 255, 255));
        jB_cancelarAlterarCurso.setText("Cancelar");
        jB_cancelarAlterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarAlterarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jB_cancelarAlterarCurso);
        jB_cancelarAlterarCurso.setBounds(330, 480, 110, 33);

        jB_buscarAlterarCurso.setBackground(new java.awt.Color(0, 204, 51));
        jB_buscarAlterarCurso.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_buscarAlterarCurso.setForeground(new java.awt.Color(255, 255, 255));
        jB_buscarAlterarCurso.setText("Buscar");
        jB_buscarAlterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_buscarAlterarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jB_buscarAlterarCurso);
        jB_buscarAlterarCurso.setBounds(160, 100, 110, 33);

        jLabel7.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(36, 44, 68));
        jLabel7.setText("Conceito");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(470, 330, 60, 27);

        jT_conceitoAlterarCurso.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_conceitoAlterarCurso.setForeground(new java.awt.Color(36, 44, 68));
        jT_conceitoAlterarCurso.setText(" ");
        getContentPane().add(jT_conceitoAlterarCurso);
        jT_conceitoAlterarCurso.setBounds(450, 360, 100, 30);

        jT_buscarAlterarCurso.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_buscarAlterarCurso.setForeground(new java.awt.Color(36, 44, 68));
        jT_buscarAlterarCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jT_buscarAlterarCursoKeyReleased(evt);
            }
        });
        getContentPane().add(jT_buscarAlterarCurso);
        jT_buscarAlterarCurso.setBounds(20, 100, 100, 30);

        jLabel8.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(36, 44, 68));
        jLabel8.setText("Carga Horária");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(450, 260, 110, 27);

        jLabel9.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(36, 44, 68));
        jLabel9.setText("Universidade");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(20, 270, 110, 27);

        jT_cargaAlterarCurso.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_cargaAlterarCurso.setForeground(new java.awt.Color(36, 44, 68));
        jT_cargaAlterarCurso.setText(" ");
        jT_cargaAlterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_cargaAlterarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jT_cargaAlterarCurso);
        jT_cargaAlterarCurso.setBounds(450, 290, 100, 30);

        jB_confirmarAlterarCurso1.setBackground(new java.awt.Color(0, 204, 51));
        jB_confirmarAlterarCurso1.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_confirmarAlterarCurso1.setForeground(new java.awt.Color(255, 255, 255));
        jB_confirmarAlterarCurso1.setText("Confirmar");
        jB_confirmarAlterarCurso1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_confirmarAlterarCurso1ActionPerformed(evt);
            }
        });
        getContentPane().add(jB_confirmarAlterarCurso1);
        jB_confirmarAlterarCurso1.setBounds(460, 480, 110, 33);

        jT_descricaoAlterarCurso.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jT_descricaoAlterarCurso.setForeground(new java.awt.Color(36, 44, 68));
        jT_descricaoAlterarCurso.setText(" ");
        jT_descricaoAlterarCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jT_descricaoAlterarCursoActionPerformed(evt);
            }
        });
        getContentPane().add(jT_descricaoAlterarCurso);
        jT_descricaoAlterarCurso.setBounds(20, 420, 349, 30);

        jTableBuscaCurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Nome", "Matricula"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableBuscaCurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableBuscaCursoMouseClicked(evt);
            }
        });
        jTableBuscaCurso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTableBuscaCursoKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(jTableBuscaCurso);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(20, 140, 450, 110);

        setSize(new java.awt.Dimension(629, 602));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jB_cancelarAlterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarAlterarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jB_cancelarAlterarCursoActionPerformed

    private void jB_buscarAlterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_buscarAlterarCursoActionPerformed
         if(!(jT_buscarAlterarCurso.getText().equals(""))){
             int codCurso =(Integer.parseInt(jT_buscarAlterarCurso.getText()));
             try {
                 model = control.buscarCurso(codCurso);
                    if(model!=null){
                        jT_cargaAlterarCurso.setText(String.valueOf(model.getCargaCurso()));
                        jT_conceitoAlterarCurso.setText(String.valueOf(model.getConceitoCurso()));
                        jT_descricaoAlterarCurso.setText(model.getDescricao());
                        jT_nomeAlterarCurso.setText(model.getNomeCurso());
                        jT_statusAlterarCurso.setText(String.valueOf(model.getStatusCurso()));
                        jT_universidadeAlterarCurso.setText(String.valueOf(model.getUniversidade().getCodUniversidade()));
                        numUniversidade=model.getUniversidade().getCodUniversidade();
                        buscou=1;
                    }else{
                        jT_cargaAlterarCurso.setText("");
                        jT_conceitoAlterarCurso.setText("");
                        jT_descricaoAlterarCurso.setText("");
                        jT_nomeAlterarCurso.setText("");
                        jT_statusAlterarCurso.setText("");
                        jT_universidadeAlterarCurso.setText("");
                        jT_buscarAlterarCurso.setText("");
                        buscou=0;
                        JOptionPane.showMessageDialog(null, "Este curso não existe!");
                    }
             } catch (SQLException ex) {
                 Logger.getLogger(JFrameAlterarCurso.class.getName()).log(Level.SEVERE, null, ex);
             }
        }
    }//GEN-LAST:event_jB_buscarAlterarCursoActionPerformed

    private void jB_confirmarAlterarCurso1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_confirmarAlterarCurso1ActionPerformed
        if(buscou==1){
            /*}else if(model.getUniversidadeCod()!=(Integer.parseInt(jT_universidadeAlterarCurso.getText()))){
                    JOptionPane.showMessageDialog(null,"Número da universidade não pode ser alterado!");*/
                if((jT_cargaAlterarCurso.getText().equals(""))||(jT_conceitoAlterarCurso.getText().equals(""))||(jT_descricaoAlterarCurso.getText().equals(""))||(jT_nomeAlterarCurso.getText().equals(""))||(jT_statusAlterarCurso.getText().equals(""))||(jT_universidadeAlterarCurso.getText().equals("")))
                {
                    JOptionPane.showMessageDialog(null,"Todos os campos devem ser preenchidos!");
                }else{
                    Universidade modelVerifica = new Universidade();
                    modelVerifica=null;
                    UniversidadeDAO controlVerifica = new UniversidadeDAO();
                        if(numUniversidade!=Integer.parseInt(jT_universidadeAlterarCurso.getText())){
                            try {
                              int linha = jTableBuscaCurso.getSelectedRow();  
                              modelVerifica = controlVerifica.buscarUniversidade(Integer.parseInt(jTableBuscaCurso.getValueAt(linha,1).toString()));
                            } catch (SQLException ex) {
                                Logger.getLogger(JFrameAlterarAluno.class.getName()).log(Level.SEVERE, null, ex);
                            }
                        }
                    if(modelVerifica!=null){    
                        try {
                            model.setCargaCurso(Integer.parseInt(jT_cargaAlterarCurso.getText()));
                            model.setConceitoCurso(Float.parseFloat(jT_conceitoAlterarCurso.getText()));
                            model.setDescricao(jT_descricaoAlterarCurso.getText());
                            model.setNomeCurso(jT_nomeAlterarCurso.getText());
                            model.setStatusCurso(Boolean.valueOf(jT_statusAlterarCurso.getText()));
                            control.alterarCurso(model,1,"Antonino two");
                            JOptionPane.showMessageDialog(null,"Curso alterado com sucesso!");
                            jT_cargaAlterarCurso.setText("");
                            jT_conceitoAlterarCurso.setText("");
                            jT_descricaoAlterarCurso.setText("");
                            jT_nomeAlterarCurso.setText("");
                            jT_statusAlterarCurso.setText("");
                            jT_universidadeAlterarCurso.setText("");
                            jT_buscarAlterarCurso.setText("");
                            buscou=0;
                        } catch (SQLException ex) {
                            Logger.getLogger(JFrameAlterarCurso.class.getName()).log(Level.SEVERE, null, ex);
                        }
                   }else{
                        JOptionPane.showMessageDialog(null,"O código desta universidade o qual você digitou, não existe!");
                        numUniversidade=-1;
                    } 
                }
        }else{
            JOptionPane.showMessageDialog(null, "Você deve buscar um curso primeiro!");
            jT_cargaAlterarCurso.setText("");
            jT_conceitoAlterarCurso.setText("");
            jT_descricaoAlterarCurso.setText("");
            jT_nomeAlterarCurso.setText("");
            jT_statusAlterarCurso.setText("");
            jT_universidadeAlterarCurso.setText("");
            jT_buscarAlterarCurso.setText("");
            buscou=0;
        }
    }//GEN-LAST:event_jB_confirmarAlterarCurso1ActionPerformed

    private void jT_nomeAlterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_nomeAlterarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_nomeAlterarCursoActionPerformed

    private void jT_cargaAlterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_cargaAlterarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_cargaAlterarCursoActionPerformed

    private void jT_descricaoAlterarCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jT_descricaoAlterarCursoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_descricaoAlterarCursoActionPerformed

    private void jTableBuscaCursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableBuscaCursoMouseClicked
        int linha = jTableBuscaCurso.getSelectedRow();
        model=null;
        try {
            model = control.buscarCurso(Integer.parseInt(jTableBuscaCurso.getValueAt(linha,1).toString()));
        } catch (SQLException ex) {
            Logger.getLogger(JFrameAlterarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(model!=null){
            try {
                model=null;
                model = control.buscarCurso(Integer.parseInt(jTableBuscaCurso.getValueAt(linha,1).toString()));
                //jT_nomealunoAlterarAluno.setText(jTableBuscaAluno.getValueAt(linha,0).toString());
                jT_cargaAlterarCurso.setText(String.valueOf(model.getCargaCurso()));
                jT_conceitoAlterarCurso.setText(String.valueOf(model.getConceitoCurso()));
                jT_descricaoAlterarCurso.setText(model.getDescricao());
                jT_nomeAlterarCurso.setText(model.getNomeCurso());
                jT_statusAlterarCurso.setText(String.valueOf(model.getStatusCurso()));
                jT_universidadeAlterarCurso.setText(String.valueOf(model.getUniversidade().getCodUniversidade()));
                numUniversidade=model.getUniversidade().getCodUniversidade();
                buscou=1;
            } catch (SQLException ex) {
                Logger.getLogger(JFrameAlterarAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jTableBuscaCursoMouseClicked

    private void jTableBuscaCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTableBuscaCursoKeyReleased

    }//GEN-LAST:event_jTableBuscaCursoKeyReleased

    private void jT_buscarAlterarCursoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jT_buscarAlterarCursoKeyReleased
        Vector cabecalho = new  Vector();
        cabecalho.add("Nome");
        cabecalho.add("Matricula");
        if(!jT_buscarAlterarCurso.getText().equals("")){
            try {
                DefaultTableModel nv = new DefaultTableModel(control.Pesquisar(jT_buscarAlterarCurso.getText()),cabecalho);
                jTableBuscaCurso.setModel(nv);
            } catch (Exception ex) {
                Logger.getLogger(JFrameAlterarAluno.class.getName()).log(Level.SEVERE, null, ex);
            }
       }else{
            jT_cargaAlterarCurso.setText("");
            jT_conceitoAlterarCurso.setText("");
            jT_descricaoAlterarCurso.setText("");
            jT_nomeAlterarCurso.setText("");
            jT_statusAlterarCurso.setText("");
            jT_universidadeAlterarCurso.setText("");
            jT_buscarAlterarCurso.setText("");
            buscou=0;
            DefaultTableModel nv = new DefaultTableModel(new Vector(),cabecalho);
            jTableBuscaCurso.setModel(nv);
        }

    }//GEN-LAST:event_jT_buscarAlterarCursoKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameCadastrarCurso.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameAlterarCurso().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_buscarAlterarCurso;
    private javax.swing.JButton jB_cancelarAlterarCurso;
    private javax.swing.JButton jB_confirmarAlterarCurso1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jT_buscarAlterarCurso;
    private javax.swing.JTextField jT_cargaAlterarCurso;
    private javax.swing.JTextField jT_conceitoAlterarCurso;
    private javax.swing.JTextField jT_descricaoAlterarCurso;
    private javax.swing.JTextField jT_nomeAlterarCurso;
    private javax.swing.JTextField jT_statusAlterarCurso;
    private javax.swing.JTextField jT_universidadeAlterarCurso;
    private javax.swing.JTable jTableBuscaCurso;
    private javax.swing.JTextPane jTextPane1;
    // End of variables declaration//GEN-END:variables
}
