/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.AdmDAO;
import Modelo.Administrador;
import javax.swing.JOptionPane;

/**
 *
 * @author laercio
 */
public class JFrameCadastrarAdministrador extends javax.swing.JPanel {
    
    Administrador model = new Administrador();
    AdmDAO controle = new AdmDAO();
    

    /**
     * Creates new form JFrameCadastrarAdministrador
     */
    public JFrameCadastrarAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jT_nomeAdminstrador = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jT_cpfAdministrador = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jT_ruaAdministrador = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jT_bairroAdministrador = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jT_cidadeAdministrador = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jT_cepAdministrador = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jF_dataNascAdministrador = new javax.swing.JFormattedTextField();
        jLabel22 = new javax.swing.JLabel();
        jT_foneAdministrador = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jT_emailAdministrador = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jP_senhaAdministrador = new javax.swing.JPasswordField();
        jT_ufAdministrador = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jB_cancelarCadAluno = new javax.swing.JButton();
        jB_cadastrarAluno = new javax.swing.JButton();
        jT_statusAdministrador = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        jLabel13.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(36, 44, 68));
        jLabel13.setText("Nome");

        jLabel14.setBackground(new java.awt.Color(36, 44, 68));
        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Cadastrar Administrador");
        jLabel14.setOpaque(true);

        jLabel18.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(36, 44, 68));
        jLabel18.setText("Nome");

        jLabel27.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(36, 44, 68));
        jLabel27.setText("CPF");

        jLabel19.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(36, 44, 68));
        jLabel19.setText("Rua");

        jLabel26.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(36, 44, 68));
        jLabel26.setText("Bairro");

        jLabel20.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(36, 44, 68));
        jLabel20.setText("Cidade");

        jLabel11.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(36, 44, 68));
        jLabel11.setText("CEP");

        jLabel21.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(36, 44, 68));
        jLabel21.setText("Data de Nascimento");

        jLabel22.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(36, 44, 68));
        jLabel22.setText("Telefone");

        jLabel15.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(36, 44, 68));
        jLabel15.setText("Senha");

        jLabel16.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(36, 44, 68));
        jLabel16.setText("Status");

        jLabel17.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(36, 44, 68));
        jLabel17.setText("e-mail");

        jB_cancelarCadAluno.setBackground(new java.awt.Color(255, 51, 51));
        jB_cancelarCadAluno.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_cancelarCadAluno.setForeground(new java.awt.Color(255, 255, 255));
        jB_cancelarCadAluno.setText("Cancelar");
        jB_cancelarCadAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cancelarCadAlunoActionPerformed(evt);
            }
        });

        jB_cadastrarAluno.setBackground(new java.awt.Color(0, 204, 51));
        jB_cadastrarAluno.setFont(new java.awt.Font("Agency FB", 0, 20)); // NOI18N
        jB_cadastrarAluno.setForeground(new java.awt.Color(255, 255, 255));
        jB_cadastrarAluno.setText("Cadastrar");
        jB_cadastrarAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_cadastrarAlunoActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Agency FB", 0, 22)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(36, 44, 68));
        jLabel12.setText("UF");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, 977, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_cpfAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel27)
                                    .addComponent(jT_nomeAdminstrador, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18)
                                    .addComponent(jLabel19)
                                    .addComponent(jT_ruaAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(184, 184, 184)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21)
                                    .addComponent(jT_foneAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jF_dataNascAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel17)
                                    .addComponent(jT_emailAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel20)
                                    .addComponent(jT_bairroAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel26)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(264, 264, 264)
                                        .addComponent(jLabel12))
                                    .addComponent(jT_cidadeAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(184, 184, 184)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jT_statusAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15)
                                    .addComponent(jP_senhaAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jT_cepAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(76, 76, 76)
                                .addComponent(jT_ufAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(391, 391, 391)
                        .addComponent(jB_cancelarCadAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jB_cadastrarAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_nomeAdminstrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jF_dataNascAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_cpfAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_foneAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jT_emailAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jT_ruaAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel16)
                        .addGap(12, 12, 12)
                        .addComponent(jT_statusAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel15)
                            .addComponent(jLabel26))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jP_senhaAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jT_bairroAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jT_cidadeAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel11))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel12)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jT_cepAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jT_ufAdministrador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jB_cancelarCadAluno)
                            .addComponent(jB_cadastrarAluno))))
                .addGap(0, 18, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jB_cancelarCadAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cancelarCadAlunoActionPerformed
        Object[] options = { "Sim", "Não" };
        int opcao = JOptionPane.showOptionDialog(null, "Deseja realmente cancelar o cadastro?", "Cancelar Cadastro", JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE , null, options, options[0]);
        System.out.println("opcao "+opcao);

        if(opcao==0){
            setDefaultCloseOperation(JFrameCadastrarAdministrador.DISPOSE_ON_CLOSE);
            System.exit(0);
        }else{}
    }//GEN-LAST:event_jB_cancelarCadAlunoActionPerformed

    private void jB_cadastrarAlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_cadastrarAlunoActionPerformed

        try {
            //Validação dos campos quando vazios!
            if((jT_nomeAdminstrador.getText().trim().equals("") ||  jT_ruaAdministrador.getText().trim().equals("") ||
                jT_cidadeAdministrador.getText().trim().equals(" ") || jT_emailAdministrador.getText().trim().equals("") ||
                jT_anoIngressoCadAluno.getText().trim().equals("") || jT_cursoCadAluno.getText().trim().isEmpty() ||
                jF_dataNascAdministrador.getText().trim().equals("") || jT_foneAdministrador.getText().trim().equals("")) ||
            jT_cepAdministrador.getText().trim().equals("") || jT_craCadAluno.getText().trim().equals("")||
            jT_ufCadAluno.getText().trim().equals("")|| jT_statusCadAluno.getText().trim().equals("") ||
            jP_senhaCadAluno.getText().trim().equals("") || jT_bairroAdministrador.getText().trim().equals("") || jT_cpfAdministrador.getText().trim().equals("")

        ){
            JOptionPane.showMessageDialog(null, "Todos os campos tem que está preenchidos!");
        }else{

            model.setNome(jT_nomeAdminstrador.getText());
            model.setRua(jT_ruaAdministrador.getText());
            model.setCidade(jT_cidadeAdministrador.getText());
            model.setEmail(jT_emailAdministrador.getText());
            model.setAnoIngressante(jT_anoIngressoCadAluno.getText());
            model.setCpf(jT_cpfAdministrador.getText());
            model.getCurso().setCodCurso(Integer.parseInt(jT_cursoCadAluno.getText()));
            model.setTelefone(jT_foneAdministrador.getText());
            model.setCep(jT_cepAdministrador.getText());
            model.setCra(Float.parseFloat(jT_craCadAluno.getText()));
            model.setUf((String) jT_ufCadAluno.getText());
            model.setStatus(Boolean.parseBoolean(jT_statusCadAluno.getText()));
            model.setSenha(jP_senhaCadAluno.getText());
            model.setBairro(jT_bairroAdministrador.getText());

            //Aluno aluno = new Aluno(model.getMatricula(),cursodao.buscarCurso(model.getCurso().getCodCurso()),model.getCra(),model.getAnoIngressante(),model.getNome(),model.getSenha(),model.getCpf(),model.getDataNascimento(),model.getCidade(),model.getUf(),model.getRua(),model.getBairro(),model.getTelefone(),model.getCep(),model.getEmail(),model.getStatus());

            controle.loginAluno(model.getMatricula(), model.getSenha());
            controle.cadastrarAluno(model,model.getMatricula(),model.getNome());
            JOptionPane.showMessageDialog(null, "Novo usuario cadastrado com sucesso!");

            //Limpar os campos após o cadastro!
            jT_nomeAdminstrador.setText("");
            jT_cpfAdministrador.setText("");
            jT_ruaAdministrador.setText(" ");
            jT_cidadeAdministrador.setText("");
            jT_emailAdministrador.setText("");
            jT_anoIngressoCadAluno.setText("");
            jT_cursoCadAluno.setText(""); //Falta Implementar o autocomplete.
            jT_foneAdministrador.setText("");
            jT_cepAdministrador.setText("");
            jT_craCadAluno.setText("");
            jT_ufCadAluno.setText("");
            jT_statusCadAluno.setText("");
            jP_senhaCadAluno.setText("");
            jT_bairroAdministrador.setText("");

        }//Fim do Else
        } catch (SQLException ex) {
            System.out.println("entrou aqui");
            Logger.getLogger(JFrameCadastrarAluno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jB_cadastrarAlunoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB_cadastrarAluno;
    private javax.swing.JButton jB_cancelarCadAluno;
    private javax.swing.JFormattedTextField jF_dataNascAdministrador;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JPasswordField jP_senhaAdministrador;
    private javax.swing.JTextField jT_bairroAdministrador;
    private javax.swing.JTextField jT_cepAdministrador;
    private javax.swing.JTextField jT_cidadeAdministrador;
    private javax.swing.JTextField jT_cpfAdministrador;
    private javax.swing.JTextField jT_emailAdministrador;
    private javax.swing.JTextField jT_foneAdministrador;
    private javax.swing.JTextField jT_nomeAdminstrador;
    private javax.swing.JTextField jT_ruaAdministrador;
    private javax.swing.JTextField jT_statusAdministrador;
    private javax.swing.JTextField jT_ufAdministrador;
    // End of variables declaration//GEN-END:variables
}
